### ISSUE TITLE
Cannot launch AppScan Source scan in node

### ISSUE THREAD

**Issue by joaomdiogo** [jenkinsci/ibm-security-appscansource-scanner-plugin#1]
Hello. I'm trying to use this plugin to trigger a scan in a remote slave node. The master only calls and launches the node, which would do all the work. So the node has AppScan Source installed and running locally.
There are some verifications being done in method AppScanSourceBuilder.perform() that cause to fail the launch of the scan:

``` java
boolean applicationFileOk = false;
if(!checkApplicationFileName(this.applicationFile)){
        logger.println(applicationFileNameValidationError);
    } else {
        if(!checkApplicationFileNameExists(this.applicationFile)){
            logger.println(this.applicationFile + " does not exist.");
        } else {
            applicationFileOk = true;
        }
}

//Check that we can access the scan workspace
boolean scanWorkspaceOk = checkScanWorkspace(this.scanWorkspace);
```

`applicationFile` and `scanWorkspace` are received and stored by the constructor:

``` java
// Fields in config.jelly must match the parameter names in the "DataBoundConstructor"
@DataBoundConstructor
public AppScanSourceBuilder(String installation, boolean disableScan, String scanWorkspace, String applicationFile, boolean acceptSSL) {
    this.disableScan=disableScan;
    this.scanWorkspace=scanWorkspace;
    this.applicationFile=applicationFile;
    this.installation=installation;
    this.acceptSSL=acceptSSL;  
}
```

The Jenkins console output is this:

> C:\jenkins\workspace\sonar-plugin\sonar-plugin.paf does not exist.
> Scan Workspace does not exist.
> C:\jenkins\workspace\sonar-plugin
> Please resolve issues with your application file or scan workspace configuration.

The problem (in my case) is that the plugin is looking for the project file (.paf) on Master-side, and the scan is being done Slave-side, which is odd. For instance, if I **replicate** the same path Master-side that is being used on Slava-side for workspace, which directory **only** contains the .paf file, the plugin works normally and the scan is executed Slave-side, as supposed to.
I'll provide more info if needed. AppScan Source v9.0.3.0.237; Jenkins v2.11. Thanks!

**Comment by kevinfealey** [comment]
Thanks for all of the detailed info! I believe I fixed the issue, though I don't have a multi-node Jenkins environment available to test at the moment. The key problem was that I was referencing files via a Java File object, but I believe I needed to use a Jenkins FilePath object, which should look for files on the correct node. Please try release 1.0.3 in the GitHub Release section, and let me know if you still have that or any other issues:
https://github.com/jenkinsci/ibm-security-appscansource-scanner-plugin/releases

As a separate note, I just noticed that our previous release was not in the Jenkins update center. If I've done everything properly, this release should appear there in the next 8 hours, so hopefully you can install the plugin directly from Jenkins.

Edit:
Not sure if you were building from source or if you downloaded from the release folder. In case you're not building yourself, I added a built version of the plugin to the release folder:
https://github.com/jenkinsci/ibm-security-appscansource-scanner-plugin/tree/master/release

**Comment by joaomdiogo** [comment]
Hello. Thank you for the fast update and sorry for not providing feedback yesterday, hadn't any possibility to do so.
Unfortunately I see the issue still persists for me, the plugin is still looking for the .paf file and workspace directory Master-side before proceeding. I'll provide more info if needed.
For the record, I was actually building the plugin before uploading it to Jenkins.

**Comment by joaomdiogo** [comment]
I'm sorry for the last post. I wasn't having the actual contextual environment to test the plugin. I've tested it properly and now I can confirm that the issue is fixed. Can run 4 different scans tiggered on the Master-node and executed on the Slave-node with no problem. Thank you.
![jenkins triggering scan](https://cloud.githubusercontent.com/assets/16403017/16585916/0bacbf2a-42bb-11e6-9628-bd93a47b383a.JPG)

**Comment by kevinfealey** [comment]
Awesome! Thanks for letting me know, as I was just starting to look into why it wasn't working :)

**Comment by maebedico** [comment]
This is a great!! i am trying to research on the same set up.

Joaodomingo - would you be able to provide be guide on how to set up appscan to run on jenkins client/slave? The appscan plugin guide mentions about having appscan and jenkins on same host, not sure how to do configure it on slave host instead.

**Comment by kevinfealey** [comment]
I don't have a test environment to set this up on right now, but if you create a new installation in the Jenkins global settings, then select that installation within a job before execution on a slave, Jenkins should use that path on the slave. 

So for example:
Master:
AppScan Source installed at:
C:\Program Files(x86)\IBM\AppScan Source

Slave:
AppScan Source installed at:
C:\OtherFolder\IBM\AppScan Source

In your Jenkins Global Settings, you should create both installations. Then when configuring the job you intend to run on a slave, select the slave's installation.

Have you tried that? Please let me know how it turns out.

**Comment by maebedico** [comment]
This is the set up I have.

> Jenkins Master on Linux Host
> 
> AppScan on Windows
> Jenkins Slave/Client on windows (same host as the appscan)

When I trigger the job from Jenkins, I am getting the error 

10:11:12 Scan Workspace does not exist.
10:11:12 C:\Users\Administrator\Desktop\ScanResults
10:11:12 C:\Users\Administrator\Desktop\Java_Common_Services\Java_Test_2.paf does not exist.
10:11:12 Please resolve issues with your application file or scan workspace configuration.

All the files mentioned to be missing are on the Windows box.

**Comment by kevinfealey** [comment]
@maebedico I'm going to have to look into this a bit since I don't have much experience with multi-node Jenkins environments. I don't have a clear understanding of which node is checking for those files and why - since it seems the master is probably checking for them, but the slave should be if it's running on the slave, since I believe that's how it was implemented. Is there any more output you think might be helpful?

If you're interested, I'd be up for doing a screen-sharing session with you some time to see if I can get a better handle on the problem to fix. Otherwise it'll probably be a few weeks before I get around to digging into this...

**Comment by andreapn1709** [comment]
@kevinfealey @maebedico I got the same problem mentioned in this topic, currently i'm using CloudBees Jenkins 2.32.1.1 (Amazon Linux) with AppScan Source Plugin ver1.0.5, and AppScan Source Server (Windows Server 2012 R2). I configure AppScan Server as a slave of Jenkins. When i build a job with remote mode on AppScan slave using appscan source plugin, i get the error message:

> Scan Workspace does not exist.
> C:\workspace\Test_AppScan
> C:\workspace\Test_AppScan\AppScanTestProject.paf does not exist.

The problem is that plugin just only check folder on master, not check on slave, i tried so many way but can not resolve, anyone can help me? Many thanks.
